# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dca408a2420eb23547b4e0dc184097b3f7d4beb29458466809c4696967cfb1f76419f3d9b49bbbf446fd51b7d9a4003e60133d7f07b8166199547ee7fd47b43

test:
  secret_key_base: aeb6dd7d6f30974ad9df99f7ea01b62528a1eef72e88f28408cbad04f18e0f853dc9071c36ddf4c3d903ae06548add50140fc6fa5dafd74f90dc15728d2fd31b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
